### ISSUE TITLE
CORS issue on the app deployed to Heroku

### ISSUE THREAD

**Issue by Simek** [farshed/genius-lyrics-api#10]
Refs #3 

I'm currently experience CORS issue on the app deployed to Heroku:

> Access to XMLHttpRequest at 'https://api.genius.com/search?q=xxxx' from origin 'https://xxx.herokuapp.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

Code is working fine locally in the Chrome with `--disable-web-security` flag.

`genius-lyrics-api` version : 3.0.3

**Comment by farshed** [comment]
Hey @Simek, this does not seem like an issue with the package but an issue with the environment instead. It uses Genius API to scrape lyrics and what origins Genius allows or blocks is out of our control. What you can do is either use the library on the server side or maybe try a different deployment platform
