### ISSUE TITLE
Axios dependency security vulnerability

### ISSUE THREAD

**Issue by casillano** [farshed/genius-lyrics-api#12]
Axios issue: https://github.com/advisories/GHSA-4w2v-q235-vp99

Dependabot cannot automatically fix this issue in my repository. it says: 

"The latest possible version that can be installed is 0.19.2 because of the following conflicting dependency:
genius-lyrics-api@3.0.4 requires axios@^0.19.0
The earliest fixed version is 0.21.1."

**Comment by farshed** [comment]
Fixed in https://github.com/farshed/genius-lyrics-api/commit/23bd2e77d39ef1d4e4d1c4f2b56ba58680470e13
