### ISSUE TITLE
The searchSong() method is not working properly with special characters.

### ISSUE THREAD

**Issue by Aylor222** [farshed/genius-lyrics-api#13]
Special characters present in a search query such as "&" are not properly encoded with the encodeURI() method present inside of the searchSong() method. 

For example ;
the requested song :  _Safe & Sound by Taylor Swift_
will return the song:  _It Ain't Safe by Skepta (Ft. A$AP Bari)_

Possible fix:
Replace the method encoreURI() with encodeURIComponent(). This change will make the above example return the good song. However, I didn't do a large test sample to ensure the effectiveness of this change for different combinations of songs and special character like (&, ?, etc.)

**Comment by farshed** [comment]
Thanks for reporting. Fixed in https://github.com/farshed/genius-lyrics-api/commit/ec8020bd31f22757d16e7eb9b9b3d888ea4bd840
