### ISSUE TITLE
Please add support for optional genius api host address

### ISSUE THREAD

**Issue by vitaliikravets** [farshed/genius-lyrics-api#14]
I would like to use this library from browser.
In order to fight the CORS , improve performance and lower the load on actual API, I am setting up a CDN that will have the same domain name as my website but will redirect all calls to genius.com.

**Comment by farshed** [comment]
Hey, that's a valid use case. I'll have to rewrite some parts of the lib to support this so give me a few days ;)

**Comment by farshed** [comment]
@vitaliikravets Could you please elaborate your use case a bit more?

**Comment by vitaliikravets** [comment]
Hi @farshed, i would like to make requests to genius api on client-side. This is obviously failing due to CORS. One could use a proxy to do those requests (CDN is an option). In that case library would make requests to your own domain (no CORS issues), while proxy is configured to redirect to api.genius.com.

**Comment by farshed** [comment]
@vitaliikravets The CORS issue should be fixed in the latest release. Do check it out and let me know if it doesn't work for you.

**Comment by vitaliikravets** [comment]
hi @farshed sorry for the late reply. Can you please point me to the fix for CORS issue?

**Comment by farshed** [comment]
@vitaliikravets sending the auth token in url params instead of header fixes the CORS issue. Here's the commit: https://github.com/farshed/genius-lyrics-api/commit/5924964912bb4ecce1c2f67d622b1d8e25826519

**Comment by vitaliikravets** [comment]
I think there is a misunderstanding. I would like to use genius-lyrics-api library in a browser, client-side, not back-end, no NodeJS.
In that case requests to api.genius.com will be done from my website (let's say mywebsite.com) and there would be a domain mismatch. Browsers, by default, do not allow making AJAX requests from mywebsite.com to api.genius.com. AJAX requests from mywebsite.com can only be done to mywebsite.com. This is guarded by CORS mechanism.

**Comment by farshed** [comment]
@vitaliikravets As far as I know, the package works fine on the browser side. There was a CORS issue in some cases when request was made from client-side but it's been fixed. If you're still getting a CORS error, do let me know.
