### ISSUE TITLE
403 on Server but not on my Desktop

### ISSUE THREAD

**Issue by tatsumara** [farshed/genius-lyrics-api#21]
as in the title, using the library works just fine on my desktop but once the code is ran on my server it just 403's.

**Comment by farshed** [comment]
Genius.com is probably blocking your server's IP due to too many requests. I would suggest you use it on the client-side so each client requests from its own IP.

**Comment by tatsumara** [comment]
that could be a possibility but i don't make anywhere close enough requests to have that be the main issue

**Comment by farshed** [comment]
That's strange. Could you please share your code so we can be sure?

**Comment by nicokimmel** [comment]
I got the same problem. Its working on my computer but when I push it to the server it only returns 403. Maybe its the reverse proxy, that causes the issue.

Code is quite simple:
`function getLyrics(title) {
	var searchOptions = {
		title: title,
		artist: " ",
		apiKey: "XXX",
		optimizeQuery: true
	}
	genius.getLyrics(searchOptions).then((lyrics) => {
		console.log(lyrics);
	});
}`

**Comment by mepc36** [comment]
Bump, seeing the same issue...will reply back if I find a fix!

**Comment by tatsumara** [comment]
since i just got a notification for this:
with another library i've tracked it down to that genius has probably blocked my ip. i verified this by connecting to my server with a vpn and then opening the genius website, where i was asked to fill in a captcha. so i don't think there's much you can fix here
