### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by ashleygyngell** [farshed/genius-lyrics-api#27]
Hey! Getting a Cross-Origin Request Blocked response from Genius on local host and on Netlify. 

Is there an updated workaround for this? 

Cheers!

**Comment by farshed** [comment]
Hi, sorry there's no getting around third-party CORS errors. You'll have to use it on the server side. The readme was misleading on this so I've updated it.

**Comment by ashleygyngell** [comment]
No problem, I had suspected that might be the solution - thanks :D

**Comment by abhilashmnair** [comment]
Hi @farshed, I am new to this. 😬 I might sound stupid, but can you advise me or give me any reference for what you mean by `use on the server side`? Thanks.

**Comment by farshed** [comment]
I somehow overlooked the notification it seems. Sorry about that. And it's fine really, none of us are born knowing that. Server side simply means in the backend i.e. the code is executed on a computer that's not yours. Or in other words, this library's code won't work in a browser environment. You might want to read about the "Client-Server model" or how the internet works. Let me know if you've any more questions.
