### ISSUE TITLE
Question: How can I export this library as a module to be used inside a webpage?

### ISSUE THREAD

**Issue by inglesuniversal** [farshed/genius-lyrics-api#32]
Do I need to run any build npm or yarn command first?

Can this script run independently on a website?

or - Does it strictly depend of a Node.js server in order to run in production?

Thanks for your help and support!

**Comment by farshed** [comment]
- No you don't need to build anything. Just install & run.
- It only supports **non-browser** environments so you'll likely need to use it server-side.
