### ISSUE TITLE
Confused about the implementation

### ISSUE THREAD

**Issue by Selbi182** [farshed/genius-lyrics-api#34]
Hey there, I got a question about the way this tool is implemented: Why do I need an API token? From the looks of it, you're scraping the lyrics directly from the official webpage anyway. Wouldn't it make more sense to fetch lyrics through Genius' API?

**Comment by farshed** [comment]
Genius API doesn't have an endpoint for returning lyrics. The API is used for searching songs and getting the link to the lyrics page (where we then scrape the lyrics from).

**Comment by farshed** [comment]
I noticed something a while ago that can potentially be used to directly fetch the lyrics and that is Genius's internal edit lyrics API. It returns the lyrics as plain text which is displayed to the user for editing. I'd welcome a PR if anyone's interested in looking into that.

**Comment by Selbi182** [comment]
Wait what? Genius, the website whose main selling point is lyrics, has an API that returns anything BUT lyrics? Why even have an API then???

**Comment by Selbi182** [comment]
> I noticed something a while ago that can potentially be used to directly fetch the lyrics and that is Genius's internal edit lyrics API. It returns the lyrics as plain text which is displayed to the user for editing. I'd welcome a PR if anyone's interested in looking into that.

What endpoint is that?

**Comment by farshed** [comment]
> Wait what? Genius, the website whose main selling point is lyrics, has an API that returns anything BUT lyrics? Why even have an API then???

I believe the purpose of the API is to bring traffic to Genius web pages. Having an endpoint that returns lyrics as well would drive the traffic AWAY from Genius and hurt whatever they have for a business model. There might be legal issues with lyrics copyright as well.

 > What endpoint is that?

https://genius.com/api/songs/3365691/lyrics_for_edit_proposal?text_format=html%2Cmarkdown

It takes a song ID and returns the lyrics for it as plain text. Quite nice 😈. Let me know if you're interested in creating a PR for it. Otherwise, I would do it.

**Comment by Selbi182** [comment]
> I believe the purpose of the API is to bring traffic to Genius web pages. Having an endpoint that returns lyrics as well would drive the traffic AWAY from Genius and hurt whatever they have for a business model. There might be legal issues with lyrics copyright as well.

Okay, that actually makes some sense. Although then I still wonder why they even bothered with an API in the first place. Oh well.

> Let me know if you're interested in creating a PR for it. Otherwise, I would do it.
Unfortunately, I don't actually work with JavaScript that much. I only discovered this page because I was looking for other people implementing the Genius API and was wondering how they did it because my own efforts had me brickwalled at actually _getting_ the lyrics. I didn't know it wasn't even part of it.

Thanks for the link though! I'll try and see if that works for my usecase :)

**Comment by Selbi182** [comment]
Hmm, from the looks of it, that URL only works while logged into Genius (like the actual website). In a private tab it doesn't work, and thus also not from a serverside application. What a shame...

**Comment by farshed** [comment]
Try this. Open the URL in a tab (non-private), open the network tab in chrome dev tools and catch the request, right-click the request, and choose "copy as cURL". Then paste it into your terminal and hit enter. If it works (which I'm sure it will), you only need to replicate that cURL request in your code somehow (it might just be really hard to implement programmatically in case they're using a rotating token for auth). Let me know how it goes if you try it.

**Comment by Selbi182** [comment]
I just can't get this to work. I tried every terminal I have installed (git bash, PowerShell, regular old cmd), but no matter what I do, I never get a result. It waits roughly half a second, then simply exists without any results:

![grafik](https://github.com/farshed/genius-lyrics-api/assets/8850085/8fe6cbd8-4a9d-42e8-9ee6-9c76a9185a7f)

Either way, however, it looks like this won't be a stable long-term solution anyway. I don't think these guys will keep the cookies unchanged indefinitely.

**Comment by farshed** [comment]
Okay, I got it to work. It seems the response is cached by the browser and when the endpoint returns 304, the browser just shows the cached version. When you copy that 304'ed request as cURL, it doesn't work in the terminal (since no cache there).

To fix it, hard refresh the page when you catch the request in the network tab so it fetches a new response instead of falling back to the cache. The status code will be 200 for a fresh request. Then copy and use that in the terminal.

<img width="1199" alt="Screenshot 2023-07-02 at 2 32 51 AM" src="https://github.com/farshed/genius-lyrics-api/assets/23633421/2d0fb51c-edf1-4abc-8b57-cc102cd34b51">



> Either way, however, it looks like this won't be a stable long-term solution anyway. I don't think these guys will keep the cookies unchanged indefinitely.

You're probably right.

**Comment by Selbi182** [comment]
Oh, that actually did the trick! It was the cache after all. Thanks!

I'm still not 100% convinced that this is a stable solution, but it's the best shot I got so far, so I guess I'll go with it until something better pops up. Thanks for all your time and help! :)

**Comment by farshed** [comment]
Glad to help :)

**Comment by Selbi182** [comment]
FYI, one more thing I just found out: Looks like the only thing required to make this work is the cookie, and within the cookie all you need is the user_credentials value.

![grafik](https://github.com/farshed/genius-lyrics-api/assets/8850085/6954ffd0-5a4f-462f-bc07-86febe3fec08)

**Comment by farshed** [comment]
Nice, that simplifies things quite a bit. `user_credentials` cookie seems to have a Max-Age of 3 months btw.

**Comment by Selbi182** [comment]
Not perfect, but at least better than once a day or something lol
