### ISSUE TITLE
Getting a weird page from law.justia.com instead of lyrics

### ISSUE THREAD

**Issue by SemionVino** [farshed/genius-lyrics-api#37]
When trying to fetch the lyrics for the song `"I Killed A Man (Live in Moscow)"` by the artist `"Slaughter To Prevail"`,
somehow i get the contents of [this page](https://law.justia.com/cases/michigan/supreme-court/1980/57376-0.html).

Code:
const options = {
       apiKey: Bun.env.CLIENT_ACCESS_TOKEN,
       title: "I Killed A Man (Live in Moscow)",
       artist: "Slaughter To Prevail",
      optimizeQuery: true,
    };
    const rawLyrics = await getLyrics(options);
    console.log(rawLyrics);

It's very weird, any idea for how that's happening?

**Comment by farshed** [comment]
Can you please share the output?

**Comment by SemionVino** [comment]
It's extremely long, basically the whole content of the case presented on that link. Start with : `Citation: 409 Mich. 672\n\nFITZGERALD, J.\n\nThe existence and scope of the felony-murder`
![Uploading Screenshot 2024-01-07 at 18.36.39.png…]()

**Comment by SemionVino** [comment]
It's extremely long, basically the whole content of the case presented on that link. Start with : Citation: 409 Mich. 672\n\nFITZGERALD, J.\n\nThe existence and scope of the felony-murder
<img width="1512" alt="Screenshot 2024-01-07 at 18 36 39" src="https://github.com/farshed/genius-lyrics-api/assets/53710793/32e307b7-afd8-4eed-b9eb-f6fc3bb1c6ed">

**Comment by SemionVino** [comment]
I've found that page by googling some of the content i received. I believe that you would get the same result if you'll request that specific song

**Comment by farshed** [comment]
I believe you're getting the lyrics for [this song](https://genius.com/Supreme-court-of-michigan-people-v-aaron-annotated).

**Comment by SemionVino** [comment]
Guess you're right. But still, it's a long way from the song i requested. Any idea why?

**Comment by farshed** [comment]
@SemionVino The `getLyrics` function searches the song via Genius API and returns the lyrics for the first search result by default. For more accuracy, I would recommend using the `searchSong` function, doing a fuzzy search on the search results and then fetch lyrics for the closest match using `getSongById`.
