### ISSUE TITLE
Response format parameter missing

### ISSUE THREAD

**Issue by shuiiiiiii** [farshed/genius-lyrics-api#39]
getLyrics function works fine but it returns the lyrics in strings, official genius API docs has this responseFormat parameter, to plain, html, or dom, look into it.

https://docs.genius.com/#/response-format-h1

**Comment by farshed** [comment]
There's no Genius API endpoint that returns lyrics for a given song. This package directly scrapes the lyrics from the Genius website.

**Comment by shuiiiiiii** [comment]
alright! ty
