### ISSUE TITLE
Help to implement app [No issue]

### ISSUE THREAD

**Issue by juanamm** [farshed/genius-lyrics-api#6]
Dear,
I'm a novice in all this, but reading I'm doing things.
I have a js app that gets the artist name and song name that plays on an online radio and stores them in `currentArtist` and `currentSong` variables
I want to combine your app to get the lyric.
```
this.refreshLyric = function (currentSong, currentArtist) {
		
		//testing API genius
		
		......
		
	}
```
Could you explain to me as a child what code should I put in my app so that it returns a `lyrics` variable with the lyrics of the song?
Best regards,
Juan

**Comment by farshed** [comment]
You can use the `getLyrics` method to get the lyrics for a specific song.

```
import { getLyrics } from 'genius-lyrics-api';

this.refreshLyric = function (currentSong, currentArtist) {
		let options = {
	                 apiKey: <YOUR GENIUS ACCESS TOKEN>,
	                 title: currentSong,
	                 artist: currentArtist,
	                 optimizeQuery: true
                     };

             return getLyrics(options);
}
```

Then,
```
this.refreshLyric(currentSong, currentArtist).then(lyrics => {
        // do something with the lyrics here
        console.log('lyrics: ', lyrics)
});
```

**Comment by juanamm** [comment]
@farshed, thanks for your kind response.
I'm going to be honest with you, I'm new to this and I'm learning.
I inserted those lines into my script.js and it gives me this error:
`Uncaught SyntaxError: Cannot use import statement outside a module`

Something is missing for your API to work.
All I did was run the command `npm install --save genius-lyrics-api`

I return this:
```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN saveError ENOENT: no such file or directory, open '/var/www/my_web.com/html/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/var/www/my_web.com/html/package.json'
npm WARN html No description
npm WARN html No repository field.
npm WARN html No README data
npm WARN html No license field.

+ genius-lyrics-api@3.0.2
added 97 packages from 182 contributors and audited 97 packages in 4.855s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
Then I didn't do anything else, I only included the lines that you shared with me in my script that is in the /js/script.js path

Obviously I'm missing steps, settings, and running your API before using it.
I have never run an API with node and I don't know what to do.

If you can indicate all the steps and commands that I must execute so that your API works I would be very grateful.

I know you are asking me it must be silly, but I cannot understand how it is executed.

**Comment by farshed** [comment]
Looks like you're using an older version of node which doesn't support esm imports. You can import the library like this instead: `const { getLyrics } = require('genius-lyrics-api');`

Also, refreshLyric method needs to be inside a class. Otherwise, you can just make it a regular function by using the `function` keyword and removing `this`.

**Comment by juanamm** [comment]
Maybe I didn't explain myself well and my English is very bad.

I am not running node.

I have a normal web HTML, CSS and I use javascript for the online radio player and to extract the name of the artist and the song that plays (script.js).

I would need to know what parameters I should add to my script.js so that it can be executed with node.
I share the [web](http://osirisradio.tk/) so that when you have time, you can see how it works.

**Comment by juanamm** [comment]
> Looks like you're using an older version of node which doesn't support esm imports. 

I am testing the code with Visual Studio Code and the latest version of node.js (v.14.6.0).

This line: `import { getLyrics } from 'genius-lyrics-api';`

Returns this error: `SyntaxError: The requested module 'genius-lyrics-api' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.`

Why module 'genius-lyrics-api' is expected to be of type CommonJS ?

I share screenshots  to see what I am doing wrong.

![genius0](https://user-images.githubusercontent.com/48572613/88141762-9b721a00-cbca-11ea-8e6e-5c46a2b91a0d.png)
![genius](https://user-images.githubusercontent.com/48572613/88141770-a167fb00-cbca-11ea-85a0-5ff24a1828cd.png)

**Comment by farshed** [comment]
Try this:
```
import geniusApi from 'genius-lyrics-api';
```
Then use it as,
```
geniusApi.getLyrics()
```

**Comment by juanamm** [comment]
@farshed, in the proposed way the usage example has worked correctly for me.

Now remember that all this arose because I need to make the API work within the javascript code that I already have.

The code was made by another developer and it works well, I have little knowledge of javascript to be able to adapt your API to what is already written.

Maybe for you it is easy to solve it, looking at the JS code that I have and you can see everything else in the link that I shared a couple of days ago.

I know that what I ask you is not part of your API, if you can not do it do not worry that I will understand it.

I will continue reading to continue learning.

Thank you very much.

**Comment by farshed** [comment]
@juanamm did the solution above not work? Does it throw some other error?

**Comment by juanamm** [comment]
> @juanamm did the solution above not work? Does it throw some other error?

I have already asked for help [here](https://stackoverflow.com/questions/63048961/pass-javascript-variables-from-a-server-node-js-to-another-web-not-embedded-jav), the problem is not your API that works very well, the problem is that I want to make it work on a traditional website (HTML, CSS, Javascript) that is hosted on a free hosting.

Then I have another server with root access in aws where the node server will work together with your API.

I came up with the idea of ​​passing the variable that contains the lyrics from the node server to the free website.

**Comment by ignmazz** [comment]
@juanamm As said on the answer of your StackOverflow post, you can call your server from your webpage by setting up a WebSocket channel, and query your Node server for the lyrics.
As it isn't an issue with the module itself, I recommend you closing this issue and posting your questions on StackOverflow or another developement community 😉 
Have a great day!

**Comment by juanamm** [comment]
@ignmazz , thanks for your answer, I left this thread open in case someone with time and desire to share could help me with that.
As I mentioned before, I am a newbie and have no idea how to do the procedure to call my server from my web page by setting up a WebSocket channel and querying my Node server to get the letters.
I understand that this help I request is not related to this excellent project.
I will close the problem as you have advised me and maybe you can explain the procedure to me and share the code with me on StackOverflow. 
I await your kind answer for the other forum. 😉
Greetings and thanks.
