### ISSUE TITLE
Song title found does not match the requested one

### ISSUE THREAD

**Issue by juanamm** [farshed/genius-lyrics-api#7]
I have requested song lyrics "Amanhã talvez" and it returns song lyrics "Tentação".

```
title: 'Amanhã talvez',
artist: 'Joanna',
```

The artist found matches, but the song title does not.

**Comment by farshed** [comment]
@juanamm It finds lyrics from genius.com. There are no lyrics for Amanhã talvez on Genius.

**Comment by juanamm** [comment]
@farshed Is there any way to compare that if the name of the requested lyrics does not match, return a message like "There are no lyrics for requested song" instead of showing any other lyrics that don't match what was requested?

**Comment by farshed** [comment]
@juanamm there's no reliable way to achieve this but you can use the `searchSong` method to manually search songs from genius.com and then only retrieve lyrics if a match is found

**Comment by juanamm** [comment]
@farshed ok, thanks for the reply.
When you can, look at the other thread to see if you can help me with the issue.
You can close this thread.
