### ISSUE TITLE
Lyrics longer than 4000 characters aren't returned

### ISSUE THREAD

**Issue by LunaRyuko** [farshed/genius-lyrics-api#9]
Hello! It seems like the library has a hardcoded limit of 4000 characters for the lyrics, was that intentional?
![Code_iZjrUB7CC3](https://user-images.githubusercontent.com/10626859/89955536-8ae61a00-dc33-11ea-9954-972acab63a7d.png)

Here's an example of a song I was trying to grab lyrics for
https://genius.com/Jay-z-and-linkin-park-points-of-authority-99-problems-one-step-closer-lyrics

**Comment by farshed** [comment]
Hey! Yes that limit was intentional to handle an edge case where Genius returns extremely long stories (actual fairytales) in response to lyrics requests. It's probably not the best way to handle that so I'm removing it for now.
